### PR TITLE
Alberto/atqr 94 endpoint update status refactor

### PR DESCRIPTION
**Pull request by albnunes**
I removed the endpoint logic

### CODE REVIEW

**Comment by albnunes** [comment]
https://linear.app/toki-labs/issue/ATQR-94/endpoint-update-status-refactor

**Review by albnunes — COMMENTED** [review]
i guess we could merge the challenge status update functions into one.

**Comment by yfernandes** [comment]
Hey @albnunes and @rairezende, I'm working on this PR review

**Review by yfernandes — COMMENTED** [review]
Everything looks fine!

**Pull request merged**
